USER_NAME := kitchen
OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no

# EXTRAFLAGS += -flto

ALLOW_WARNINGS = yes

KITCHEN_HOME_ROW_MODS = yes
