#define LAYOUT_wrapper(...) LAYOUT(__VA_ARGS__)
#define LAYOUT_reviung41_wrapper(...) LAYOUT_reviung41(__VA_ARGS__)

#define HOME_SCLN MT(MOD_LALT, DV_SCLN)
#define HOME_Q MT(MOD_LCTL, DV_Q)
#define HOME_J MT(MOD_LSFT, DV_J)
#define HOME_K MT(MOD_LGUI, DV_K)

#define HOME_M MT(MOD_LGUI, DV_M)
#define HOME_W MT(MOD_LSFT, DV_W)
#define HOME_V MT(MOD_LCTL, DV_V)
#define HOME_Z MT(MOD_LALT, DV_Z)

#define KITCHEN_LOCK G(C(DV_Q))
#define L_BASE 0
#define L_NUMBERS 1
#define L_SYMBOLS 2
#define L_NAV 3

// "standard" six column layout
#define KITCHEN_L_BASE_R1L KC_TAB, DV_QUOT, DV_COMM, DV_DOT, DV_P, DV_Y
#define KITCHEN_L_BASE_R1R DV_F, DV_G, DV_C, DV_R, DV_L, KC_NO
#define KITCHEN_L_BASE_R2L KC_ESC, DV_A, DV_O, DV_E, DV_U, DV_I
#define KITCHEN_L_BASE_R2R DV_D, DV_H, DV_T, DV_N, DV_S, DV_MINS
#define KITCHEN_L_BASE_R3L KC_NO, HOME_SCLN, HOME_Q, HOME_J, HOME_K, DV_X
#define KITCHEN_L_BASE_R3R DV_B, HOME_M, HOME_W, HOME_V, HOME_Z, KC_NO
#define KITCHEN_L_BASE_THUMB_L MO(L_NUMBERS), LT(L_SYMBOLS, KC_BSPC), KC_NO
#define KITCHEN_L_BASE_THUMB_R KC_ENT, LT(L_NAV, KC_SPC), KC_NO
#define KITCHEN_L_BASE_5THUMB MO(L_NUMBERS), LT(L_SYMBOLS, KC_BSPC), KC_ENT, LT(L_NAV, KC_SPC), KC_NO

#define KITCHEN_L_NUMBERS_LEFT KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
#define KITCHEN_L_NUMBERS_MODS KC_NO, KC_LALT, KC_LCTL, KC_LSFT, KC_LGUI, KC_NO
#define KITCHEN_L_NUMBERS_R1R DV_LBRC, KC_7, KC_8, KC_9, DV_RBRC, KC_NO
#define KITCHEN_L_NUMBERS_R2R DV_SLSH, KC_4, KC_5, KC_6, DV_EQL, KC_NO
#define KITCHEN_L_NUMBERS_R3R KC_GRV, KC_1, KC_2, KC_3, KC_BSLS, KC_NO
#define KITCHEN_L_NUMBERS_THUMB_L KC_TRNS, KC_TRNS, KC_TRNS
#define KITCHEN_L_NUMBERS_THUMB_R DV_DOT, KC_0, DV_MINS
#define KITCHEN_L_NUMBERS_5THUMB KC_TRNS, KC_TRNS, DV_DOT, KC_0, DV_MINS

#define KITCHEN_L_SYMBOLS_LEFT KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
#define KITCHEN_L_SYMBOLS_MODS KC_NO, KC_LALT, KC_LCTL, KC_LSFT, KC_LGUI, KC_NO
#define KITCHEN_L_SYMBOLS_R1R DV_LCBR, KC_AMPR, KC_ASTR, KC_LPRN, DV_RCBR, KC_NO
#define KITCHEN_L_SYMBOLS_R2R DV_QUES, KC_DLR, KC_PERC, KC_CIRC, DV_PLUS, KC_NO
#define KITCHEN_L_SYMBOLS_R3R KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_PIPE, KC_NO
#define KITCHEN_L_SYMBOLS_THUMB_L KC_TRNS, KC_TRNS, KC_TRNS
#define KITCHEN_L_SYMBOLS_THUMB_R KC_LPRN, KC_RPRN, DV_UNDS
#define KITCHEN_L_SYMBOLS_5THUMB KC_TRNS, KC_TRNS, KC_LPRN, KC_RPRN, DV_UNDS

#define KITCHEN_L_NAV_R1L LGUI(KC_GRV), RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO
#define KITCHEN_L_NAV_R2L KC_TRNS, RGB_MOD, RGB_VAI, LGUI(DV_LCBR), LGUI(DV_RCBR), KC_NO
#define KITCHEN_L_NAV_R3L KC_TRNS, RGB_RMOD, RGB_VAD, LGUI(DV_LBRC), LGUI(DV_RBRC), KC_NO
// TODO: probably replace the home with cmd-left and end with cmd-right
#define KITCHEN_L_NAV_R1R KC_PGUP, KC_HOME, KC_UP, KC_END, KC_NO, KC_NO
#define KITCHEN_L_NAV_R2R KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO
#define KITCHEN_L_NAV_R3R LGUI(LCTL(DV_Q)), KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_NO
#define KITCHEN_L_NAV_THUMB KC_TRNS, KC_TRNS, KC_TRNS
#define KITCHEN_L_NAV_5THUMB KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

// Configure the global tapping term (default: 200ms)
#define TAPPING_TERM 200

// Prevent normal rollover on alphas from accidentally triggering mods.
#define IGNORE_MOD_TAP_INTERRUPT

// Enable rapid switch from tap to hold, disables double tap hold auto-repeat.
#define TAPPING_FORCE_HOLD

// Apply the modifier on keys that are tapped during a short hold of a modtap
#define PERMISSIVE_HOLD
